package modelo;
// Generated 19-nov-2019 9:21:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private int idEquipo;
     private String marca;
     private String modelo;
     private String descripcion;
     private int pulgadasPantalla;
     private int capacidadDisco;
     private int gbMemoria;
     private BigDecimal precio;

    public Equipos() {
    }

    public Equipos(int idEquipo, String marca, String modelo, String descripcion, int pulgadasPantalla, int capacidadDisco, int gbMemoria, BigDecimal precio) {
       this.idEquipo = idEquipo;
       this.marca = marca;
       this.modelo = modelo;
       this.descripcion = descripcion;
       this.pulgadasPantalla = pulgadasPantalla;
       this.capacidadDisco = capacidadDisco;
       this.gbMemoria = gbMemoria;
       this.precio = precio;
    }
   
    public int getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getPulgadasPantalla() {
        return this.pulgadasPantalla;
    }
    
    public void setPulgadasPantalla(int pulgadasPantalla) {
        this.pulgadasPantalla = pulgadasPantalla;
    }
    public int getCapacidadDisco() {
        return this.capacidadDisco;
    }
    
    public void setCapacidadDisco(int capacidadDisco) {
        this.capacidadDisco = capacidadDisco;
    }
    public int getGbMemoria() {
        return this.gbMemoria;
    }
    
    public void setGbMemoria(int gbMemoria) {
        this.gbMemoria = gbMemoria;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }

    @Override
    public String toString() {
        return "idEquipo: " + idEquipo + " marca: " + marca + " modelo: " + modelo + " descripcion: " + descripcion + " pulgadasPantalla: " + pulgadasPantalla + " capacidadDisco: " + capacidadDisco + " gbMemoria: " + gbMemoria + " precio: " + precio;
    }
    
    




}


